@baseUrl=https://api.spotify.com
@clientId=c4c4f6600a6e49db9d6805d7245eedac

###
GET {{baseUrl}}/authorize
    ?client_id={{clientId}}
    &response_type=code
    &redirect_uri=http://localhost:3000
    &scope=streaming user-top-read user-read-playback-position user-follow-read user-follow-modify playlist-modify-public
